# Generated by Django 2.2 on 2019-04-20 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banks',
            new_name='Bank',
        ),
        migrations.RenameModel(
            old_name='Branches',
            new_name='Branch',
        ),
    ]
